// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi2_5OaUr5auwBXfS-C8F3hhfb7m-DR3U',
    appId: '1:390906904595:web:25b6e9dce23b5a646dbfe6',
    messagingSenderId: '390906904595',
    projectId: 'interneepk-ae4f1',
    authDomain: 'interneepk-ae4f1.firebaseapp.com',
    storageBucket: 'interneepk-ae4f1.appspot.com',
    measurementId: 'G-NT9S6KNSWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAfiFIiBbeDH2SFNYXwW8YBIhQAo7jddU',
    appId: '1:390906904595:android:542a4165cd5f79316dbfe6',
    messagingSenderId: '390906904595',
    projectId: 'interneepk-ae4f1',
    storageBucket: 'interneepk-ae4f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiZQNqa9PA5irNk45SiUHVJBLBwNSZDHc',
    appId: '1:390906904595:ios:5ebe86c0fe669b636dbfe6',
    messagingSenderId: '390906904595',
    projectId: 'interneepk-ae4f1',
    storageBucket: 'interneepk-ae4f1.appspot.com',
    iosBundleId: 'com.example.interneePk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiZQNqa9PA5irNk45SiUHVJBLBwNSZDHc',
    appId: '1:390906904595:ios:5ebe86c0fe669b636dbfe6',
    messagingSenderId: '390906904595',
    projectId: 'interneepk-ae4f1',
    storageBucket: 'interneepk-ae4f1.appspot.com',
    iosBundleId: 'com.example.interneePk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi2_5OaUr5auwBXfS-C8F3hhfb7m-DR3U',
    appId: '1:390906904595:web:b4c2fb19d045f7f86dbfe6',
    messagingSenderId: '390906904595',
    projectId: 'interneepk-ae4f1',
    authDomain: 'interneepk-ae4f1.firebaseapp.com',
    storageBucket: 'interneepk-ae4f1.appspot.com',
    measurementId: 'G-813Y8J03F4',
  );
}
